## Coding Challenge 7: Maps

In this notebook, I use Harvard Atlas ECI to map the Economic Complexity of countries

Link to data:
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/XTAQMC

In [ ]:
%pip install altair   # Some packages need to be installed to the virtual machine before we can import them into our notebook. We can do this with '!pip install'

Note: you may need to restart the kernel to use updated packages.

ERROR: Invalid requirement: '#'

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd
import numpy as np
import altair as alt
from json import loads, dumps

### Importing data

In [2]:
eci = pd.read_stata("../data/rankings.dta") # ECI Rankings
country_code = pd.read_csv('../data/location_country.csv') # Country codes

In [3]:
eci.head()

   country_id  year  sitc_eci  hs_eci  growth_proj sitc_eci_rank  hs_eci_rank
0           4  1980       NaN     0.0          NaN                         72
1           8  1980       NaN     0.0          NaN                         72
2          12  1980       NaN     0.0          NaN                         72
3          24  1980       NaN     0.0          NaN                         72
4          31  1980       NaN     0.0          NaN                         72

In [4]:
country_code.head()

   country_id name_short_en iso3_code  legacy_location_id
0         533         Aruba       ABW                   0
1           4   Afghanistan       AFG                   1
2          24        Angola       AGO                   2
3         660      Anguilla       AIA                   3
4           8       Albania       ALB                   4

### Cleaning

In [5]:
# Only data from 2000's
eci = eci[eci['year']>=2000]

# Merge with country code
eci_country_code = pd.merge(eci, country_code, on="country_id")

# Keeping key columns
#eci_country_code = eci_country_code[['year','name_short_en', 'iso3_code','hs_eci_rank']]

eci_country_code

# Renaming columns
eci_country_code.rename(columns={

    "name_short_en" : "country",
    "iso3_code": "ISO3"

}, inplace=True)

eci_country_code

,country_id,year,sitc_eci,hs_eci,growth_proj,sitc_eci_rank,hs_eci_rank,country,ISO3,legacy_location_id
0,4,2000,-0.315885,-0.155740,NaN,78,72,Afghanistan,AFG,1
1,8,2000,-0.125142,-0.196624,NaN,71,75,Albania,ALB,4
2,12,2000,-0.985822,-1.039474,NaN,123,126,Algeria,DZA,66
3,24,2000,-1.909197,-2.031919,NaN,141,142,Angola,AGO,2
4,31,2000,-0.367642,-0.133683,NaN,81,71,Azerbaijan,AZE,16
...,...,...,...,...,...,...,...,...,...,...
3330,858,2022,0.097432,0.081263,1.494,57,59,Uruguay,URY,230
3331,860,2022,-0.046318,-0.146699,6.148,66,71,Uzbekistan,UZB,232
3332,862,2022,-1.014992,-0.862514,0.937,124,109,Venezuela,VEN,236
3333,887,2022,-0.706749,-1.093413,3.749,103,125,Yemen,YEM,243
3334,894,2022,-0.809530,-0.723531,3.368,112,99,Zambia,ZMB,247

### Change in the Complexity index of European countries, from the creation of the EU to now (1993 to 2022).

In [11]:
eci_country_code['hs_eci_1993'] = eci_country_code[eci_country_code['year'] == 1993].set_index('country_id')['hs_eci']
eci_country_code['hs_eci_2022'] = eci_country_code[eci_country_code['year'] == 2022].set_index('country_id')['hs_eci']
eci_country_code['hs_eci_1993_2022'] = (eci_country_code['hs_eci_2022'] - eci_country_code['hs_eci_1993']) / eci_country_code['hs_eci_1993']

In [12]:
eci_country_code

,country_id,year,sitc_eci,hs_eci,growth_proj,sitc_eci_rank,hs_eci_rank,country,ISO3,legacy_location_id,change_1993_2022,hs_eci_1993,hs_eci_2022,hs_eci_1993_2022
0,4,2000,-0.315885,-0.155740,NaN,78,72,Afghanistan,AFG,1,72.0,NaN,NaN,NaN
1,8,2000,-0.125142,-0.196624,NaN,71,75,Albania,ALB,4,75.0,NaN,NaN,NaN
2,12,2000,-0.985822,-1.039474,NaN,123,126,Algeria,DZA,66,126.0,NaN,NaN,NaN
3,24,2000,-1.909197,-2.031919,NaN,141,142,Angola,AGO,2,142.0,NaN,NaN,NaN
4,31,2000,-0.367642,-0.133683,NaN,81,71,Azerbaijan,AZE,16,71.0,NaN,-1.316216,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3330,858,2022,0.097432,0.081263,1.494,57,59,Uruguay,URY,230,NaN,NaN,NaN,NaN
3331,860,2022,-0.046318,-0.146699,6.148,66,71,Uzbekistan,UZB,232,NaN,NaN,NaN,NaN
3332,862,2022,-1.014992,-0.862514,0.937,124,109,Venezuela,VEN,236,NaN,NaN,NaN,NaN
3333,887,2022,-0.706749,-1.093413,3.749,103,125,Yemen,YEM,243,NaN,NaN,NaN,NaN
3334,894,2022,-0.809530,-0.723531,3.368,112,99,Zambia,ZMB,247,NaN,NaN,NaN,NaN

### Exporting as CSV

In [13]:
# Only 2022
eci_country_code_2022 = eci_country_code[eci_country_code['year'] ==2022]

eci_country_code_2022.to_csv('../datamap_data2022.csv', index=False)

### Plotting

I do not have to plot since I already have the JSON plot from the course seminar